### ISSUE TITLE
No license is specified

### ISSUE THREAD

**Issue by ociaw** [statiqdev/Docable#18]
What license is Docable licensed under, if any? I've been customizing it a bit and may want to publish a new theme at some point, but at the moment I can't do that since I've used Docable as a base.

**Comment by daveaglick** [comment]
Excellent point! I need to add license files to all the themes so it's obvious. Docable (and CleanBlog, and any future official themes) are all MIT licensed the same as Statiq Framework. The only non-MIT licenses apply to Statiq Web and Statiq Docs as those represent significant additional effort and an "open core" licensing model - though read the [licensing FAQ](https://www.statiq.dev/support/) since most individual users won't exceed the licensing limits and can use them for free as well (though contributions are always appreciated).

I'll add some license files to the themes right now.
