### ISSUE TITLE
ArgumentNullException when starting Docs site with theme as a submodule

### ISSUE THREAD

**Issue by tbolon** [statiqdev/Docable#42]
Hi,

I have followed the getting started doc for Statiq.Docs website, and cloned the Docable theme as a submodule:

```
 git submodule add https://github.com/statiqdev/Docable.git theme
```

But I am now receiving an error when starting the website:

```
[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » RenderRazor » [C:/code/tests/connect.statiq/theme/input/index.cshtml => index.html] Value cannot be null. (Parameter 'key')
[DBUG] Exception while executing pipeline Content/PostProcess: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Common.IDocumentExtensions.GetTitle(IDocument document)
   at AspNetCore._Shared__RightNavigation.ExecuteAsync() in Shared/_RightNavigation.cshtml:line 12
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore._Shared__Navigation.ExecuteAsync() in Shared/_Navigation.cshtml:line 23
   ...
```

I have cloned the theme in my project directory:

```
.vscode/
bin/
cache/
input/ <= single index.md
obj/
output/
temp/
theme/ <= submodule
wwwrooot/
.gitmodules
Connect.Statiq.csproj
Program.cs
```

Is this layout correct? It seems statiq tries to read the `theme/input/index.cshtml` from the submodule which is empty

**Comment by daveaglick** [comment]
It's picking up the `theme/input/index.cshtml` file correctly, that's what the `[C:/code/tests/connect.statiq/theme/input/index.cshtml => index.html]` in the top part of the error means (read that as "the file located on disk at "C:/code/tests/connect.statiq/theme/input/index.cshtml" that is intended to write to the output folder at "/index.html").

This looks like a bug, but I'm having hard time tracking it down. What follows is my stream-of-consciousness about where the problem is, so no worries if you don't follow it.

The error is happening inside the `IDocument.GetTitle()` method which looks like this:
```
public static string GetTitle(this IDocument document) =>
    _titles.GetOrAdd(document, doc => doc.GetString(Keys.Title) ?? doc.Source.GetTitle());
```
In particular, the key to the `_titles` dictionary appears to be null - in other words, `document` is null here. That shouldn't ever really be the case at the call site in `_RightNavigation.cshtml` since the `document` comes from a call to `OutputPages.GetChildrenOf(indexFileName)`:
```
foreach(IDocument doc in OutputPages.GetChildrenOf(indexFileName)
    // Ensure the API path is added even if it's not a direct child of the root page
    .Concat(OutputPages.Get(NormalizedPath.Combine(Context.GetPath(DocsKeys.ApiPath), indexFileName)))
    .Where(x => x.GetBool(SiteKeys.ShowInNavigation, true))
    // Ensure that duplicate API links aren't shown 
    .Distinct()
    .OrderBy(x => x.GetInt(Keys.Order)))
{
    <li class="nav-item">
        @Html.DocumentLink(
            doc,
            doc.GetString(SiteKeys.NavigationTitle, doc.GetTitle()),
            new Dictionary<object, object> { { "class", "nav-link" } })
    </li>
}
```

I'm going to continue trying to reproduce this with a fresh clone of Docable.

**Comment by daveaglick** [comment]
Okay, I can reproduce now - looking into it further...

**Comment by daveaglick** [comment]
I'm starting to wonder if this is a difference in .NET 7. I can reproduce the problem if I follow the quick start instructions like you did, and I'm seeing it in the Statiq website itself. Which doesn't make a lot of sense given that hasn't changed in a while and it runs successfully every night via GitHub Actions.

In your case, I think it _might_ be because there's no `api` path being generated. That's likely one bug that needs to be patched in Docable: don't crash if there's no `api` folder. You can get it to move past that particular error by adding an `/input/api/index.md` file.

But the Statiq website failing to build locally is also _another_ issue that I think is related. After some digging, I think that problem might be due to some differences between .NET versions in how globbing is working. I still need to spend some time investigating, but I'll stay on this issue until I get to the bottom of it - sit tight.

**Comment by tbolon** [comment]
Thank you Dave, I should have stated that I had no api in this case.

In my case, I just wanted to create a website with a documentation theme and features (but no c# code), so I decided to start with Docs and the Docable theme.

Perhaps I would not have faced this bug if I started with Web package and still used Docable... Anyway, I hope it will help others.

Thanks 🙏
